FROM bitnami/spark:3.5

USER root

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app
COPY pyproject.toml .

# Install dependencies
RUN uv sync --all-extras

EXPOSE 8888 8501 8000 4040

CMD ["uv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
